import { Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { LanguageService } from '../../core/i18n/language.service';

type LandingCopy = { [Key in keyof typeof ENGLISH_COPY]: string };

const ENGLISH_COPY = {
  eyebrow: 'Your next goal starts here',
  titleStart: 'The gam‘eya you know.',
  titleAccent: 'Made simpler.',
  description: 'Find a money circle that fits your goal, contribution, and timeline—then take your next step with confidence.',
  browse: 'Find Your Circle',
  account: 'See How It Works',
  signIn: 'I already have an account',
  guestNote: 'No account needed to browse or apply',
  visualLabel: 'Your circle journey',
  visualTitle: 'One clear path to membership',
  listing: 'Find your circle',
  listingMeta: 'Compare amount, duration & slots',
  apply: 'Send your application',
  applyMeta: 'Apply as a guest or member',
  verified: 'Complete verification',
  verifiedMeta: 'Review and agreement follow',
  progress: 'Application journey',
  stepOne: 'Applied',
  stepTwo: 'Review',
  stepThree: 'Verified',
  valueEyebrow: 'Built for confidence',
  valueTitle: 'Know what happens before you commit',
  valueDescription: 'Aman Money Loop makes the membership journey visible, from the first search to final activation.',
  benefitOneTitle: 'Browse openly',
  benefitOneText: 'Search open circles by contribution, duration, and available slots without signing in.',
  benefitTwoTitle: 'See the full picture',
  benefitTwoText: 'Review circle terms and availability before deciding whether the opportunity fits your goal.',
  benefitThreeTitle: 'Follow a clear process',
  benefitThreeText: 'Application, organizer review, verification, agreement, onboarding, then activation.',
  howEyebrow: 'How it works',
  howTitle: 'From browsing to belonging',
  howDescription: 'A straightforward membership journey with a clear next step at every stage.',
  howOneTitle: 'Explore circles',
  howOneText: 'Compare open listings and choose the contribution and duration that suit you.',
  howTwoTitle: 'Apply your way',
  howTwoText: 'Apply as a guest, or create an account to reuse your saved profile details.',
  howThreeTitle: 'Get reviewed',
  howThreeText: 'The organizer reviews your application and schedules verification if you are shortlisted.',
  howFourTitle: 'Join the loop',
  howFourText: 'Accept your agreement, finish onboarding, and become an active circle member.',
  guestEyebrow: 'New to money circles?',
  guestTitle: 'Start by looking. Register when you’re ready.',
  guestText: 'The marketplace is open to everyone. Explore real listing terms first, then apply as a guest or member.',
  guestAction: 'Browse without signing in',
  ctaEyebrow: 'Ready when you are',
  ctaTitle: 'Find a circle that fits your next goal.',
  ctaText: 'Explore the marketplace today. Creating an account makes future applications and status tracking easier.',
  ctaPrimary: 'Explore marketplace',
  ctaSecondary: 'Create my account',
  footerText: 'A clearer way to join and manage digital money circles.',
  privacy: 'Transparent journey',
  guestAccess: 'Guest access',
  copyright: '© 2026 Aman Money Loop',
} as const;

const ARABIC_COPY: LandingCopy = {
  eyebrow: 'هدفك القادم يبدأ هنا',
  titleStart: 'الجمعية اللي تعرفها،',
  titleAccent: 'بطريقة أبسط.',
  description: 'اعثر على جمعية تناسب هدفك وقسطك والمدة التي تختارها، وابدأ خطوتك القادمة بثقة.',
  browse: 'اعثر على جمعيتك',
  account: 'اعرف كيف تعمل',
  signIn: 'لديّ حساب بالفعل',
  guestNote: 'لا تحتاج إلى حساب للتصفح أو التقديم',
  visualLabel: 'رحلتك في الجمعية',
  visualTitle: 'طريق واحد واضح للعضوية',
  listing: 'اختر جمعيتك',
  listingMeta: 'قارن القسط والمدة والأماكن',
  apply: 'أرسل طلبك',
  applyMeta: 'قدّم كزائر أو كعضو',
  verified: 'أكمل التحقق',
  verifiedMeta: 'ثم المراجعة والاتفاقية',
  progress: 'مراحل طلبك',
  stepOne: 'تم التقديم',
  stepTwo: 'المراجعة',
  stepThree: 'التحقق',
  valueEyebrow: 'مصمم ليمنحك الثقة',
  valueTitle: 'اعرف كل خطوة قبل أن تلتزم',
  valueDescription: 'يجعل أمان موني لوب رحلة العضوية واضحة، من أول بحث وحتى التفعيل النهائي.',
  benefitOneTitle: 'تصفّح بحرية',
  benefitOneText: 'ابحث في الجمعيات المتاحة حسب القسط والمدة والأماكن الشاغرة دون تسجيل الدخول.',
  benefitTwoTitle: 'شاهد الصورة كاملة',
  benefitTwoText: 'راجع شروط الجمعية والأماكن المتاحة قبل أن تقرر إن كانت تناسب هدفك.',
  benefitThreeTitle: 'اتبع مساراً واضحاً',
  benefitThreeText: 'طلب، ثم مراجعة المنظّم، فالتحقق والاتفاقية والتهيئة، وأخيراً التفعيل.',
  howEyebrow: 'كيف تعمل المنصة؟',
  howTitle: 'من التصفّح إلى العضوية',
  howDescription: 'رحلة عضوية بسيطة، وخطوة تالية واضحة في كل مرحلة.',
  howOneTitle: 'استكشف الجمعيات',
  howOneText: 'قارن الإعلانات المتاحة واختر القسط والمدة المناسبين لك.',
  howTwoTitle: 'قدّم بالطريقة التي تناسبك',
  howTwoText: 'قدّم كزائر، أو أنشئ حساباً لاستخدام بيانات ملفك في الطلبات القادمة.',
  howThreeTitle: 'تابع المراجعة',
  howThreeText: 'يراجع المنظّم طلبك ويحدد موعد التحقق عند إدراجك في القائمة المختصرة.',
  howFourTitle: 'انضم إلى الجمعية',
  howFourText: 'اقبل الاتفاقية، وأكمل التهيئة، وابدأ كعضو فعّال في الجمعية.',
  guestEyebrow: 'الجمعيات جديدة عليك؟',
  guestTitle: 'ابدأ بالتصفّح، وسجّل عندما تكون جاهزاً.',
  guestText: 'السوق متاح للجميع. اطّلع أولاً على شروط الجمعيات الحقيقية، ثم قدّم كزائر أو كعضو.',
  guestAction: 'تصفّح دون تسجيل الدخول',
  ctaEyebrow: 'ابدأ وقتما تشاء',
  ctaTitle: 'اعثر على جمعية تناسب هدفك القادم.',
  ctaText: 'استكشف السوق اليوم. إنشاء حساب يسهّل طلباتك القادمة ومتابعة حالتها.',
  ctaPrimary: 'استكشف السوق',
  ctaSecondary: 'أنشئ حسابي',
  footerText: 'طريقة أوضح للانضمام إلى الجمعيات المالية الرقمية وإدارتها.',
  privacy: 'رحلة شفافة',
  guestAccess: 'دخول الزوار',
  copyright: '© 2026 أمان موني لوب',
};

@Component({
  selector: 'app-landing',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './landing.component.html',
  styleUrl: './landing.component.scss',
})
export class LandingComponent {
  readonly language = inject(LanguageService);

  get copy(): LandingCopy {
    return this.language.isArabic() ? ARABIC_COPY : ENGLISH_COPY;
  }
}
